all:
	@gcc rm.c -o rm
	@gcc date.c -o date
	@gcc mkdir.c -o dir
	@gcc cat.c -o cato
	@gcc ls.c -o lso
	@gcc shell.c
	@./a.out
	@echo all flies made

clean:
	@rm rm
	@rm date
	@rm dir
	@rm cato
	@rm lso
	@rm a.out
	@echo Cleaning complete
